lang: en-US
title: My Awesome Site
email: 
description: 
baseurl: # the optional subpath of your site, e.g. "/blog"
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
author:	
  name: neo-lestat
  twitter: 
  picture: 
  twitter_username: neo_lestat
github_username: neo-lestat
logo:
remote_theme: mmistakes/jekyll-theme-basically-basic
